project 'IoTtest.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IoTtest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SQLite.swift', '~> 0.11.4'
  pod 'Charts', '~> 3.1.1'

   # Pods for IoTtest

end
